### ISSUE TITLE
Tried it on 18.04 and failes (fyi)

### ISSUE THREAD

**Issue by vonglahn** [riegercloud/install-nextcloud#15]
I tried it on an brandnew Ubuntu 18.04 and get an "Internal Server Error" after install and ssl.

**Comment by riegercloud** [comment]
thank you. could you provide further information. WIP regarding 18.04

**Comment by vonglahn** [comment]
Hi,

I'm not shure which part do you excately mean. But when I comment the two memcache lines. Nothing happens.
What informations can I provide to you to help you?

**Comment by riegercloud** [comment]
The new script is already released!
Please give it a trial on a fres OS.

otherwise:
change redis from socket (0) to 6379 and comment the lines with the unis sockets (/etc/redis/redis.conf)
restart redis-server
then ammend the config.php 
'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0.0,
  ),
...now your cloud should be reachable again?!

**Comment by vonglahn** [comment]
I'll give it a try on monday.

**Comment by vonglahn** [comment]
Hi Carsten,

it works. Thanks a lot for this script.

**Comment by riegercloud** [comment]
Great - Thank you very much!
